### ISSUE TITLE
Possible attack vector using temporaryZipPath?

### ISSUE THREAD

**Issue by hoffie** [ProdriveTechnologies/hpraid_exporter#1]
First of all, thanks for developing and publishing this exporter!

I noticed that it is suggested to run this exporter as root.
At the same time, a constant `--hpraid.temporary-zip-path` must be set during start.

This sounds like a local user with write access to this path would be able to influence this privileged exporter in bad ways:
- If `ssacli` will overwrite the target file (haven't checked), there is a good chance that a local user could create a symlink pointing to some privileged file (such as /etc/passwd) and `ssacli` would overwrite it
- If `ssacli` uses `open()` with the `O_CREAT` and `O_EXCL` flags (I guess this is rather unlikely), the local user could break this exporter by pre-generating this file and making ssacli fail.

I therefore suggest one of the following:
- Use an unpredictable temporary file name instead (e.g. [ioutil.Tempfile](https://golang.org/pkg/io/ioutil/#TempFile) for each `ssacli` call or [ioutil.TempDir](https://golang.org/pkg/io/ioutil/#TempDir) on startup)
- Explicitly advise users to set `--hpraid.temporary-zip-path` to a path which is only writable by root (and drop the default `/tmp`)

**Comment by EdSchouten** [comment]
Hi there! Using `ioutil.TempDir` sounds like a good idea. One command line flag to remove. Interested in sending a pull request? Thanks in advance!

**Comment by mickael-carl** [comment]
I think this can be closed now, thanks to #2. Thanks @hoffie for reporting and contributing!
